#!/bin/bash


LIST=$1

# TODO add check in case $LIST is empty string or not being passed

# save to variable list of address from specified mlmmj-list
# double trick: 
# - the stdout result from the mlmmj command is flattened from a multiline print
#   to a one line of values divided by empty space *when* saved to a variable
# - we can wrap this value directly inside an array `R=()`, and let bash array
#   to split the string by empty space

ORIGINLIST=($(sudo /usr/bin/mlmmj-list -L /var/spool/mlmmj/$LIST))

# loop over full member-list and create a new array with members
# not found in ./members; those have been randomly chosen already
# fairly dumb approach but works fine

CHOSEN=$(<./.members)

LISTADDRESS=()
for member in "${ORIGINLIST[@]}"; do
  
  # check if current member is NOT present in $CHOSEN (use `!`)
  # see <https://stackoverflow.com/a/231298>
  if [[ ! $CHOSEN =~ $member ]]; then
    LISTADDRESS+=($member)
  fi
   
done

# pick a random member from the list
# and append it do .members
# -gt => greater than; see <https://askubuntu.com/a/1042664>
SIZE=${#LISTADDRESS[@]}

if [ $SIZE -gt 0 ]; then
  IDX=$((RANDOM % $SIZE))

  echo ${LISTADDRESS[$IDX]} >> ./.members
  echo ${LISTADDRESS[$IDX]}
else
  echo "$SIZE"
fi

